version: '3.8'

services:
  eventarb-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; conn = sqlite3.connect('/app/data/trades.db'); conn.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:

